steps:
  build-docs:
    image: pcit/vuepress
    with:
      dir: .

  upload-docs:
    image: pcit/pages
    if:
      status: success
      event: ['push']
    with:
      keep_history: true
      # target_branch: gh-pages
      git_url: github.com/pcit-ce/docs
      local_dir: .vuepress/dist
      # email: ${EMAIL}
      # username: khs1994
      git_token: ${GITHUB_TOKEN}

  upload-docs-to-gitee:
    image: pcit/pages
    if:
      status: success
      event: ['push']
    with:
      keep_history: true
      # target_branch: gh-pages
      git_url: gitee.com/pcit-ce/pcit-ce
      local_dir: .vuepress/dist
      # email: ${EMAIL}
      username: khs1994
      git_token: ${GITEE_TOKEN}
